// Managed weaver bot workflow - autonomous task creation and management.
// Run `weaver eject` to customize.

import { weaverLoadConfig } from '../node-types/load-config.js';
import { weaverDetectProvider } from '../node-types/detect-provider.js';
import { weaverReceiveTask } from '../node-types/receive-task.js';
import { weaverRouteTask } from '../node-types/route-task.js';
import { weaverReadWorkflow } from '../node-types/read-workflow.js';
import { weaverBuildContext } from '../node-types/build-context.js';
import { weaverPlanTask } from '../node-types/plan-task.js';
import { weaverApprovalGate } from '../node-types/approval-gate.js';
import { weaverAbortTask } from '../node-types/abort-task.js';
import { weaverExecValidateRetry } from '../node-types/exec-validate-retry.js';
import { weaverGitOps } from '../node-types/git-ops.js';
import { weaverSendNotify } from '../node-types/send-notify.js';
import { weaverBotReport } from '../node-types/bot-report.js';

/**
 * Autonomous workflow bot. Routes by task type, branches on approval,
 * retries validation failures via scoped execution, fans out to git
 * and notifications in parallel, merges all paths at report.
 *
 * @flowWeaver workflow
 *
 * @node cfg      weaverLoadConfig       [color: "teal"]     [icon: "settings"]       [position: 200 200]
 * @node detect   weaverDetectProvider   [color: "cyan"]     [icon: "search"]         [position: 400 200]
 * @node receive  weaverReceiveTask      [color: "blue"]     [icon: "send"]           [position: 600 200]
 * @node route    weaverRouteTask        [color: "purple"]   [icon: "flow"]           [position: 800 200]
 *
 * @node readWf   weaverReadWorkflow     [color: "cyan"]     [icon: "description"]    [position: 1000 450]
 *
 * @node context  weaverBuildContext     [color: "teal"]     [icon: "code"]           [position: 1000 200]
 * @node plan     weaverPlanTask         [color: "blue"]     [icon: "psychology"]     [position: 1200 200]
 * @node approve  weaverApprovalGate     [color: "orange"]   [icon: "send"]           [position: 1400 200]
 *
 * @node abort    weaverAbortTask        [color: "red"]      [icon: "code"]           [position: 1600 450]
 *
 * @node execRetry weaverExecValidateRetry [color: "purple"] [icon: "code"]           [position: 1600 200]
 *
 * @node gitOps   weaverGitOps           [color: "green"]    [icon: "code"]           [position: 1800 100]
 * @node notify   weaverSendNotify       [color: "yellow"]   [icon: "send"]           [position: 1800 300]
 *
 * @node report   weaverBotReport        [color: "green"]    [icon: "description"]    [position: 2000 200]
 *
 * @path Start -> cfg -> detect -> receive -> route -> context -> plan -> approve -> execRetry -> gitOps -> report -> Exit
 * @path execRetry -> notify
 * @path route:fail -> readWf
 * @path approve:fail -> abort
 *
 * @connect readWf.onSuccess -> report.execute
 * @connect abort.onSuccess -> report.execute
 * @connect notify.onSuccess -> report.execute
 *
 * @connect gitOps.ctx -> report.mainCtx
 * @connect readWf.ctx -> report.readCtx
 * @connect abort.ctx -> report.abortCtx
 *
 * @connect report.summary -> Exit.summary
 *
 * @position Start 0 200
 * @position Exit 2200 200
 *
 * @param execute [order:-1] - Execute
 * @param taskJson [order:0] [optional] - Task instruction (JSON)
 * @param projectDir [order:1] [optional] - Project directory
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] [hidden] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaverBot(
  execute: boolean,
  taskJson?: string,
  projectDir?: string,
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // (auto-generated by compiler)
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
