// Managed weaver bot workflow - autonomous task creation and management.
// Run `weaver eject` to customize.

import { weaverLoadConfig } from '../node-types/load-config.js';
import { weaverDetectProvider } from '../node-types/detect-provider.js';
import { weaverReceiveTask } from '../node-types/receive-task.js';
import { weaverRouteTask } from '../node-types/route-task.js';
import { weaverReadWorkflow } from '../node-types/read-workflow.js';
import { weaverBuildContext } from '../node-types/build-context.js';
import { weaverPlanTask } from '../node-types/plan-task.js';
import { weaverApprovalGate } from '../node-types/approval-gate.js';
import { weaverAbortTask } from '../node-types/abort-task.js';
import { weaverExecValidateRetry } from '../node-types/exec-validate-retry.js';
import { weaverGitOps } from '../node-types/git-ops.js';
import { weaverSendNotify } from '../node-types/send-notify.js';
import { weaverBotReport } from '../node-types/bot-report.js';

// @flow-weaver-runtime-start
// ============================================================================
// DO NOT EDIT - This section is auto-generated by Flow Weaver
// ============================================================================

import { GeneratedExecutionContext, CancellationError } from '@synergenius/flow-weaver/runtime';
import type { TDebugger, TDebugController } from '@synergenius/flow-weaver/runtime';
declare const __flowWeaverDebugger__: TDebugger | undefined;
// @flow-weaver-runtime-end

/**
 * @flowWeaver workflow
 * @node cfg weaverLoadConfig [color: "teal"] [icon: "settings"] [position: 200 200]
 * @node detect weaverDetectProvider [color: "cyan"] [icon: "search"] [position: 400 200]
 * @node receive weaverReceiveTask [color: "blue"] [icon: "send"] [position: 600 200]
 * @node route weaverRouteTask [color: "purple"] [icon: "flow"] [position: 800 200]
 * @node readWf weaverReadWorkflow [color: "cyan"] [icon: "description"] [position: 1000 450]
 * @node context weaverBuildContext [color: "teal"] [icon: "code"] [position: 1000 200]
 * @node plan weaverPlanTask [color: "blue"] [icon: "psychology"] [position: 1200 200]
 * @node approve weaverApprovalGate [color: "orange"] [icon: "send"] [position: 1400 200]
 * @node abort weaverAbortTask [color: "red"] [icon: "code"] [position: 1600 450]
 * @node execRetry weaverExecValidateRetry [color: "purple"] [icon: "code"] [position: 1600 200]
 * @node gitOps weaverGitOps [color: "green"] [icon: "code"] [position: 1800 100]
 * @node notify weaverSendNotify [color: "yellow"] [icon: "send"] [position: 1800 300]
 * @node report weaverBotReport [color: "green"] [icon: "description"] [position: 2000 200]
 * @path Start -> cfg -> detect -> receive -> route -> context -> plan -> approve -> execRetry -> gitOps -> report -> Exit
 * @path execRetry -> notify
 * @path route:fail -> readWf
 * @path approve:fail -> abort
 * @position Start 0 200
 * @position Exit 2200 200
 * @connect readWf.onSuccess -> report.execute
 * @connect abort.onSuccess -> report.execute
 * @connect notify.onSuccess -> report.execute
 * @connect gitOps.ctx -> report.mainCtx
 * @connect readWf.ctx -> report.readCtx
 * @connect abort.ctx -> report.abortCtx
 * @connect report.summary -> Exit.summary
 * @param execute [order:-1] - Execute
 * @param taskJson [order:0] - TaskJson
 * @param projectDir [order:1] - ProjectDir
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaverBot(
  execute: boolean,
  params: { taskJson?: string; projectDir?: string },
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // ============================================================================
  // DO NOT EDIT - This section is auto-generated by Flow Weaver
  // Edit the @flowWeaver annotations above to modify workflow behavior
  // ============================================================================

    const __effectiveDebugger__ = typeof __flowWeaverDebugger__ !== 'undefined' ? __flowWeaverDebugger__ : undefined;

    // Recursion depth protection
    const __rd__ = (params as { __rd__?: number }).__rd__ ?? 0;
    if (__rd__ >= 1000) {
      throw new Error('Max recursion depth exceeded (1000) in workflow "weaverBot"');
    }

    const ctx = new GeneratedExecutionContext(true, __effectiveDebugger__, __abortSignal__);

    // Debug controller for step-through debugging and checkpoint/resume
    const __ctrl__: TDebugController = (
      typeof globalThis !== 'undefined' && (globalThis as unknown as { __fw_debug_controller__?: TDebugController }).__fw_debug_controller__
        ? (globalThis as unknown as { __fw_debug_controller__?: TDebugController }).__fw_debug_controller__
        : { beforeNode: () => true, afterNode: () => {} }
    )!;

    const startIdx = ctx.addExecution('Start');
    await ctx.setVariable({ id: 'Start', portName: 'execute', executionIndex: startIdx, nodeTypeName: 'Start' }, execute);
    await ctx.setVariable({ id: 'Start', portName: 'taskJson', executionIndex: startIdx, nodeTypeName: 'Start' }, params.taskJson);
    await ctx.setVariable({ id: 'Start', portName: 'projectDir', executionIndex: startIdx, nodeTypeName: 'Start' }, params.projectDir);
    await ctx.sendStatusChangedEvent({
      nodeTypeName: 'Start',
      id: 'Start',
      executionIndex: startIdx,
      status: 'SUCCEEDED',
    });

    let cfgIdx: number | undefined;
    let detectIdx: number | undefined;
    let receiveIdx: number | undefined;
    let routeIdx: number | undefined;
    let readWfIdx: number | undefined;
    let contextIdx: number | undefined;
    let planIdx: number | undefined;
    let approveIdx: number | undefined;
    let abortIdx: number | undefined;
    let execRetryIdx: number | undefined;
    let gitOpsIdx: number | undefined;
    let notifyIdx: number | undefined;
    let reportIdx: number | undefined;

    let cfg_success = false;
    let detect_success = false;
    let receive_success = false;

    if (await __ctrl__.beforeNode('cfg', ctx)) {

      // ── cfg (weaverLoadConfig) ──
      ctx.checkAborted('cfg');
      cfgIdx = ctx.addExecution('cfg');
      if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'cfg';
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverLoadConfig',
        id: 'cfg',
        executionIndex: cfgIdx,
        status: 'RUNNING',
      });

      cfg_success = false;

      try {
        await ctx.setVariable({ id: 'cfg', portName: 'execute', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, true);
        const cfg_projectDir = await ctx.getVariable({ id: 'Start', portName: 'projectDir', executionIndex: startIdx }) as string;
        await ctx.setVariable({ id: 'cfg', portName: 'projectDir', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, cfg_projectDir);
        const cfgResult = weaverLoadConfig(cfg_projectDir);
        await ctx.setVariable({ id: 'cfg', portName: 'projectDir', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, cfgResult.projectDir);
        await ctx.setVariable({ id: 'cfg', portName: 'config', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, cfgResult.config);
        await ctx.setVariable({ id: 'cfg', portName: 'onSuccess', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, true);
        await ctx.setVariable({ id: 'cfg', portName: 'onFailure', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverLoadConfig',
          id: 'cfg',
          executionIndex: cfgIdx,
          status: 'SUCCEEDED',
        });
        await __ctrl__.afterNode('cfg', ctx);
        cfg_success = true;
      } catch (error: unknown) {
        const isCancellation = CancellationError.isCancellationError(error);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverLoadConfig',
          id: 'cfg',
          executionIndex: cfgIdx,
          status: isCancellation ? 'CANCELLED' : 'FAILED',
        });
        if (!isCancellation) {
          ctx.sendLogErrorEvent({
            nodeTypeName: 'weaverLoadConfig',
            id: 'cfg',
            executionIndex: cfgIdx,
            error: error instanceof Error ? error.message : String(error),
          });
          await ctx.setVariable({ id: 'cfg', portName: 'onSuccess', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, false);
          await ctx.setVariable({ id: 'cfg', portName: 'onFailure', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, true);
          cfg_success = false;
        }
        throw error;
      }
    } else {
      cfgIdx = ctx.addExecution('cfg');
      cfg_success = true;
    }

    if (cfg_success) {
      if (await __ctrl__.beforeNode('detect', ctx)) {

        // ── detect (weaverDetectProvider) ──
        ctx.checkAborted('detect');
        detectIdx = ctx.addExecution('detect');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'detect';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverDetectProvider',
          id: 'detect',
          executionIndex: detectIdx,
          status: 'RUNNING',
        });

        detect_success = false;

        try {
          await ctx.setVariable({ id: 'detect', portName: 'execute', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, true);
          const detect_projectDir = await ctx.getVariable({ id: 'cfg', portName: 'projectDir', executionIndex: cfgIdx! }) as string;
          await ctx.setVariable({ id: 'detect', portName: 'projectDir', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, detect_projectDir);
          const detect_config = await ctx.getVariable({ id: 'cfg', portName: 'config', executionIndex: cfgIdx! }) as Parameters<typeof weaverDetectProvider>[1];
          await ctx.setVariable({ id: 'detect', portName: 'config', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, detect_config);
          const detectResult = weaverDetectProvider(detect_projectDir, detect_config);
          const detectResult_raw: unknown = detectResult;
          await ctx.setVariable({ id: 'detect', portName: 'env', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, typeof detectResult_raw === 'object' && detectResult_raw !== null && 'env' in detectResult_raw ? detectResult_raw.env : detectResult_raw);
          await ctx.setVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, true);
          await ctx.setVariable({ id: 'detect', portName: 'onFailure', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverDetectProvider',
            id: 'detect',
            executionIndex: detectIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('detect', ctx);
          detect_success = true;
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverDetectProvider',
            id: 'detect',
            executionIndex: detectIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'weaverDetectProvider',
              id: 'detect',
              executionIndex: detectIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
            await ctx.setVariable({ id: 'detect', portName: 'onFailure', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, true);
            detect_success = false;
          }
          throw error;
        }
      } else {
        detectIdx = ctx.addExecution('detect');
        detect_success = true;
      }

    } else {
      const detectIdx = ctx.addExecution('detect');
      await ctx.setVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
      await ctx.setVariable({ id: 'detect', portName: 'onFailure', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverDetectProvider',
        id: 'detect',
        executionIndex: detectIdx,
        status: 'CANCELLED',
      });
      const receiveIdx = ctx.addExecution('receive');
      await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverReceiveTask',
        id: 'receive',
        executionIndex: receiveIdx,
        status: 'CANCELLED',
      });
      const routeIdx = ctx.addExecution('route');
      await ctx.setVariable({ id: 'route', portName: 'onSuccess', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
      await ctx.setVariable({ id: 'route', portName: 'onFailure', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverRouteTask',
        id: 'route',
        executionIndex: routeIdx,
        status: 'CANCELLED',
      });
      const contextIdx = ctx.addExecution('context');
      await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBuildContext',
        id: 'context',
        executionIndex: contextIdx,
        status: 'CANCELLED',
      });
      const readWfIdx = ctx.addExecution('readWf');
      await ctx.setVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
      await ctx.setVariable({ id: 'readWf', portName: 'onFailure', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverReadWorkflow',
        id: 'readWf',
        executionIndex: readWfIdx,
        status: 'CANCELLED',
      });
    }
    if (cfg_success && detect_success) {
      if (await __ctrl__.beforeNode('receive', ctx)) {

        // ── receive (weaverReceiveTask) ──
        ctx.checkAborted('receive');
        receiveIdx = ctx.addExecution('receive');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'receive';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverReceiveTask',
          id: 'receive',
          executionIndex: receiveIdx,
          status: 'RUNNING',
        });

        receive_success = false;

        try {
          const receive_execute = await ctx.getVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx! }) as boolean;
          await ctx.setVariable({ id: 'receive', portName: 'execute', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receive_execute);
          const receive_env = await ctx.getVariable({ id: 'detect', portName: 'env', executionIndex: detectIdx! }) as Parameters<typeof weaverReceiveTask>[1];
          await ctx.setVariable({ id: 'receive', portName: 'env', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receive_env);
          const receive_taskJson = await ctx.getVariable({ id: 'Start', portName: 'taskJson', executionIndex: startIdx }) as string;
          await ctx.setVariable({ id: 'receive', portName: 'taskJson', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receive_taskJson);
          const receiveResult = await weaverReceiveTask(receive_execute, receive_env, receive_taskJson);
          await ctx.setVariable({ id: 'receive', portName: 'ctx', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receiveResult.ctx);
          await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receiveResult.onSuccess);
          await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receiveResult.onFailure);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverReceiveTask',
            id: 'receive',
            executionIndex: receiveIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('receive', ctx);
          receive_success = receiveResult.onSuccess;
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverReceiveTask',
            id: 'receive',
            executionIndex: receiveIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'weaverReceiveTask',
              id: 'receive',
              executionIndex: receiveIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
            await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, true);
            receive_success = false;
          }
          throw error;
        }
      } else {
        receiveIdx = ctx.addExecution('receive');
        receive_success = true;
      }

    } else {
      const receiveIdx = ctx.addExecution('receive');
      await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverReceiveTask',
        id: 'receive',
        executionIndex: receiveIdx,
        status: 'CANCELLED',
      });
      const routeIdx = ctx.addExecution('route');
      await ctx.setVariable({ id: 'route', portName: 'onSuccess', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
      await ctx.setVariable({ id: 'route', portName: 'onFailure', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverRouteTask',
        id: 'route',
        executionIndex: routeIdx,
        status: 'CANCELLED',
      });
      const contextIdx = ctx.addExecution('context');
      await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBuildContext',
        id: 'context',
        executionIndex: contextIdx,
        status: 'CANCELLED',
      });
      const readWfIdx = ctx.addExecution('readWf');
      await ctx.setVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
      await ctx.setVariable({ id: 'readWf', portName: 'onFailure', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverReadWorkflow',
        id: 'readWf',
        executionIndex: readWfIdx,
        status: 'CANCELLED',
      });
    }
    if (cfg_success && detect_success && receive_success) {
      let route_success = false;
      if (await __ctrl__.beforeNode('route', ctx)) {

        // ── route (weaverRouteTask) ──
        ctx.checkAborted('route');
        routeIdx = ctx.addExecution('route');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'route';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverRouteTask',
          id: 'route',
          executionIndex: routeIdx,
          status: 'RUNNING',
        });

        route_success = false;

        try {
          await ctx.setVariable({ id: 'route', portName: 'execute', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, true);
          const route_ctx = await ctx.getVariable({ id: 'receive', portName: 'ctx', executionIndex: receiveIdx! }) as string;
          await ctx.setVariable({ id: 'route', portName: 'ctx', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, route_ctx);
          const routeResult = weaverRouteTask(route_ctx);
          const routeResult_raw: unknown = routeResult;
          await ctx.setVariable({ id: 'route', portName: 'ctx', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, typeof routeResult_raw === 'object' && routeResult_raw !== null && 'ctx' in routeResult_raw ? routeResult_raw.ctx : routeResult_raw);
          await ctx.setVariable({ id: 'route', portName: 'onSuccess', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, true);
          await ctx.setVariable({ id: 'route', portName: 'onFailure', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverRouteTask',
            id: 'route',
            executionIndex: routeIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('route', ctx);
          route_success = true;
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverRouteTask',
            id: 'route',
            executionIndex: routeIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'weaverRouteTask',
              id: 'route',
              executionIndex: routeIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'route', portName: 'onSuccess', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
            await ctx.setVariable({ id: 'route', portName: 'onFailure', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, true);
            route_success = false;
          }
          const contextIdx = ctx.addExecution('context');
          await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
          await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverBuildContext',
            id: 'context',
            executionIndex: contextIdx,
            status: 'CANCELLED',
          });
          const readWfIdx = ctx.addExecution('readWf');
          await ctx.setVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
          await ctx.setVariable({ id: 'readWf', portName: 'onFailure', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverReadWorkflow',
            id: 'readWf',
            executionIndex: readWfIdx,
            status: 'CANCELLED',
          });
          throw error;
        }
      } else {
        routeIdx = ctx.addExecution('route');
        route_success = true;
      }

      if (route_success) {
        const readWfIdx = ctx.addExecution('readWf');
        await ctx.setVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
        await ctx.setVariable({ id: 'readWf', portName: 'onFailure', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverReadWorkflow',
          id: 'readWf',
          executionIndex: readWfIdx,
          status: 'CANCELLED',
        });
        let context_success = false;
        if (await __ctrl__.beforeNode('context', ctx)) {

          // ── context (weaverBuildContext) ──
          ctx.checkAborted('context');
          contextIdx = ctx.addExecution('context');
          if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'context';
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverBuildContext',
            id: 'context',
            executionIndex: contextIdx,
            status: 'RUNNING',
          });

          context_success = false;

          try {
            await ctx.setVariable({ id: 'context', portName: 'execute', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, true);
            const context_ctx = await ctx.getVariable({ id: 'route', portName: 'ctx', executionIndex: routeIdx! }) as string;
            await ctx.setVariable({ id: 'context', portName: 'ctx', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, context_ctx);
            const contextResult = weaverBuildContext(context_ctx);
            const contextResult_raw: unknown = contextResult;
            await ctx.setVariable({ id: 'context', portName: 'ctx', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, typeof contextResult_raw === 'object' && contextResult_raw !== null && 'ctx' in contextResult_raw ? contextResult_raw.ctx : contextResult_raw);
            await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, true);
            await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverBuildContext',
              id: 'context',
              executionIndex: contextIdx,
              status: 'SUCCEEDED',
            });
            await __ctrl__.afterNode('context', ctx);
            context_success = true;
          } catch (error: unknown) {
            const isCancellation = CancellationError.isCancellationError(error);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverBuildContext',
              id: 'context',
              executionIndex: contextIdx,
              status: isCancellation ? 'CANCELLED' : 'FAILED',
            });
            if (!isCancellation) {
              ctx.sendLogErrorEvent({
                nodeTypeName: 'weaverBuildContext',
                id: 'context',
                executionIndex: contextIdx,
                error: error instanceof Error ? error.message : String(error),
              });
              await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
              await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, true);
              context_success = false;
            }
            const planIdx = ctx.addExecution('plan');
            await ctx.setVariable({ id: 'plan', portName: 'onSuccess', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, false);
            await ctx.setVariable({ id: 'plan', portName: 'onFailure', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, false);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverPlanTask',
              id: 'plan',
              executionIndex: planIdx,
              status: 'CANCELLED',
            });
            throw error;
          }
        } else {
          contextIdx = ctx.addExecution('context');
          context_success = true;
        }

        if (context_success) {
          let plan_success = false;
          if (await __ctrl__.beforeNode('plan', ctx)) {

            // ── plan (weaverPlanTask) ──
            ctx.checkAborted('plan');
            planIdx = ctx.addExecution('plan');
            if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'plan';
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverPlanTask',
              id: 'plan',
              executionIndex: planIdx,
              status: 'RUNNING',
            });

            plan_success = false;

            try {
              const plan_execute = await ctx.getVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx! }) as boolean;
              await ctx.setVariable({ id: 'plan', portName: 'execute', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, plan_execute);
              const plan_ctx = await ctx.getVariable({ id: 'context', portName: 'ctx', executionIndex: contextIdx! }) as string;
              await ctx.setVariable({ id: 'plan', portName: 'ctx', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, plan_ctx);
              const planResult = await weaverPlanTask(plan_execute, plan_ctx);
              await ctx.setVariable({ id: 'plan', portName: 'ctx', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, planResult.ctx);
              await ctx.setVariable({ id: 'plan', portName: 'onSuccess', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, planResult.onSuccess);
              await ctx.setVariable({ id: 'plan', portName: 'onFailure', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, planResult.onFailure);
              await ctx.sendStatusChangedEvent({
                nodeTypeName: 'weaverPlanTask',
                id: 'plan',
                executionIndex: planIdx,
                status: 'SUCCEEDED',
              });
              await __ctrl__.afterNode('plan', ctx);
              plan_success = planResult.onSuccess;
            } catch (error: unknown) {
              const isCancellation = CancellationError.isCancellationError(error);
              await ctx.sendStatusChangedEvent({
                nodeTypeName: 'weaverPlanTask',
                id: 'plan',
                executionIndex: planIdx,
                status: isCancellation ? 'CANCELLED' : 'FAILED',
              });
              if (!isCancellation) {
                ctx.sendLogErrorEvent({
                  nodeTypeName: 'weaverPlanTask',
                  id: 'plan',
                  executionIndex: planIdx,
                  error: error instanceof Error ? error.message : String(error),
                });
                await ctx.setVariable({ id: 'plan', portName: 'onSuccess', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, false);
                await ctx.setVariable({ id: 'plan', portName: 'onFailure', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, true);
                plan_success = false;
              }
              const approveIdx = ctx.addExecution('approve');
              await ctx.setVariable({ id: 'approve', portName: 'onSuccess', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, false);
              await ctx.setVariable({ id: 'approve', portName: 'onFailure', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, false);
              await ctx.sendStatusChangedEvent({
                nodeTypeName: 'weaverApprovalGate',
                id: 'approve',
                executionIndex: approveIdx,
                status: 'CANCELLED',
              });
              throw error;
            }
          } else {
            planIdx = ctx.addExecution('plan');
            plan_success = true;
          }

          if (plan_success) {
            let approve_success = false;
            if (await __ctrl__.beforeNode('approve', ctx)) {

              // ── approve (weaverApprovalGate) ──
              ctx.checkAborted('approve');
              approveIdx = ctx.addExecution('approve');
              if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'approve';
              await ctx.sendStatusChangedEvent({
                nodeTypeName: 'weaverApprovalGate',
                id: 'approve',
                executionIndex: approveIdx,
                status: 'RUNNING',
              });

              approve_success = false;

              try {
                const approve_execute = await ctx.getVariable({ id: 'plan', portName: 'onSuccess', executionIndex: planIdx! }) as boolean;
                await ctx.setVariable({ id: 'approve', portName: 'execute', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, approve_execute);
                const approve_ctx = await ctx.getVariable({ id: 'plan', portName: 'ctx', executionIndex: planIdx! }) as string;
                await ctx.setVariable({ id: 'approve', portName: 'ctx', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, approve_ctx);
                const approveResult = await weaverApprovalGate(approve_execute, approve_ctx);
                await ctx.setVariable({ id: 'approve', portName: 'ctx', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, approveResult.ctx);
                await ctx.setVariable({ id: 'approve', portName: 'onSuccess', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, approveResult.onSuccess);
                await ctx.setVariable({ id: 'approve', portName: 'onFailure', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, approveResult.onFailure);
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverApprovalGate',
                  id: 'approve',
                  executionIndex: approveIdx,
                  status: 'SUCCEEDED',
                });
                await __ctrl__.afterNode('approve', ctx);
                approve_success = approveResult.onSuccess;
              } catch (error: unknown) {
                const isCancellation = CancellationError.isCancellationError(error);
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverApprovalGate',
                  id: 'approve',
                  executionIndex: approveIdx,
                  status: isCancellation ? 'CANCELLED' : 'FAILED',
                });
                if (!isCancellation) {
                  ctx.sendLogErrorEvent({
                    nodeTypeName: 'weaverApprovalGate',
                    id: 'approve',
                    executionIndex: approveIdx,
                    error: error instanceof Error ? error.message : String(error),
                  });
                  await ctx.setVariable({ id: 'approve', portName: 'onSuccess', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, false);
                  await ctx.setVariable({ id: 'approve', portName: 'onFailure', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, true);
                  approve_success = false;
                }
                const execRetryIdx = ctx.addExecution('execRetry');
                await ctx.setVariable({ id: 'execRetry', portName: 'onSuccess', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, false);
                await ctx.setVariable({ id: 'execRetry', portName: 'onFailure', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, false);
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverExecValidateRetry',
                  id: 'execRetry',
                  executionIndex: execRetryIdx,
                  status: 'CANCELLED',
                });
                const abortIdx = ctx.addExecution('abort');
                await ctx.setVariable({ id: 'abort', portName: 'onSuccess', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, false);
                await ctx.setVariable({ id: 'abort', portName: 'onFailure', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, false);
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverAbortTask',
                  id: 'abort',
                  executionIndex: abortIdx,
                  status: 'CANCELLED',
                });
                throw error;
              }
            } else {
              approveIdx = ctx.addExecution('approve');
              approve_success = true;
            }

            if (approve_success) {
              const abortIdx = ctx.addExecution('abort');
              await ctx.setVariable({ id: 'abort', portName: 'onSuccess', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, false);
              await ctx.setVariable({ id: 'abort', portName: 'onFailure', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, false);
              await ctx.sendStatusChangedEvent({
                nodeTypeName: 'weaverAbortTask',
                id: 'abort',
                executionIndex: abortIdx,
                status: 'CANCELLED',
              });
              let execRetry_success = false;
              if (await __ctrl__.beforeNode('execRetry', ctx)) {

                // ── execRetry (weaverExecValidateRetry) ──
                ctx.checkAborted('execRetry');
                execRetryIdx = ctx.addExecution('execRetry');
                if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'execRetry';
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverExecValidateRetry',
                  id: 'execRetry',
                  executionIndex: execRetryIdx,
                  status: 'RUNNING',
                });

                execRetry_success = false;

                try {
                  const execRetry_execute = await ctx.getVariable({ id: 'approve', portName: 'onSuccess', executionIndex: approveIdx! }) as boolean;
                  await ctx.setVariable({ id: 'execRetry', portName: 'execute', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, execRetry_execute);
                  const execRetry_ctx = await ctx.getVariable({ id: 'approve', portName: 'ctx', executionIndex: approveIdx! }) as string;
                  await ctx.setVariable({ id: 'execRetry', portName: 'ctx', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, execRetry_ctx);
                  const execRetryResult = await weaverExecValidateRetry(execRetry_execute, execRetry_ctx);
                  await ctx.setVariable({ id: 'execRetry', portName: 'ctx', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, execRetryResult.ctx);
                  await ctx.setVariable({ id: 'execRetry', portName: 'onSuccess', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, execRetryResult.onSuccess);
                  await ctx.setVariable({ id: 'execRetry', portName: 'onFailure', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, execRetryResult.onFailure);
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverExecValidateRetry',
                    id: 'execRetry',
                    executionIndex: execRetryIdx,
                    status: 'SUCCEEDED',
                  });
                  await __ctrl__.afterNode('execRetry', ctx);
                  execRetry_success = execRetryResult.onSuccess;
                } catch (error: unknown) {
                  const isCancellation = CancellationError.isCancellationError(error);
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverExecValidateRetry',
                    id: 'execRetry',
                    executionIndex: execRetryIdx,
                    status: isCancellation ? 'CANCELLED' : 'FAILED',
                  });
                  if (!isCancellation) {
                    ctx.sendLogErrorEvent({
                      nodeTypeName: 'weaverExecValidateRetry',
                      id: 'execRetry',
                      executionIndex: execRetryIdx,
                      error: error instanceof Error ? error.message : String(error),
                    });
                    await ctx.setVariable({ id: 'execRetry', portName: 'onSuccess', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, false);
                    await ctx.setVariable({ id: 'execRetry', portName: 'onFailure', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, true);
                    execRetry_success = false;
                  }
                  const gitOpsIdx = ctx.addExecution('gitOps');
                  await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
                  await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverGitOps',
                    id: 'gitOps',
                    executionIndex: gitOpsIdx,
                    status: 'CANCELLED',
                  });
                  const notifyIdx = ctx.addExecution('notify');
                  await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
                  await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverSendNotify',
                    id: 'notify',
                    executionIndex: notifyIdx,
                    status: 'CANCELLED',
                  });
                  throw error;
                }
              } else {
                execRetryIdx = ctx.addExecution('execRetry');
                execRetry_success = true;
              }

              if (execRetry_success) {
                if (await __ctrl__.beforeNode('gitOps', ctx)) {

                  // ── gitOps (weaverGitOps) ──
                  ctx.checkAborted('gitOps');
                  gitOpsIdx = ctx.addExecution('gitOps');
                  if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'gitOps';
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverGitOps',
                    id: 'gitOps',
                    executionIndex: gitOpsIdx,
                    status: 'RUNNING',
                  });

                  try {
                    await ctx.setVariable({ id: 'gitOps', portName: 'execute', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, true);
                    const gitOps_ctx = await ctx.getVariable({ id: 'execRetry', portName: 'ctx', executionIndex: execRetryIdx! }) as string;
                    await ctx.setVariable({ id: 'gitOps', portName: 'ctx', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, gitOps_ctx);
                    const gitOpsResult = weaverGitOps(gitOps_ctx);
                    const gitOpsResult_raw: unknown = gitOpsResult;
                    await ctx.setVariable({ id: 'gitOps', portName: 'ctx', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, typeof gitOpsResult_raw === 'object' && gitOpsResult_raw !== null && 'ctx' in gitOpsResult_raw ? gitOpsResult_raw.ctx : gitOpsResult_raw);
                    await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, true);
                    await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
                    await ctx.sendStatusChangedEvent({
                      nodeTypeName: 'weaverGitOps',
                      id: 'gitOps',
                      executionIndex: gitOpsIdx,
                      status: 'SUCCEEDED',
                    });
                    await __ctrl__.afterNode('gitOps', ctx);
                  } catch (error: unknown) {
                    const isCancellation = CancellationError.isCancellationError(error);
                    await ctx.sendStatusChangedEvent({
                      nodeTypeName: 'weaverGitOps',
                      id: 'gitOps',
                      executionIndex: gitOpsIdx,
                      status: isCancellation ? 'CANCELLED' : 'FAILED',
                    });
                    if (!isCancellation) {
                      ctx.sendLogErrorEvent({
                        nodeTypeName: 'weaverGitOps',
                        id: 'gitOps',
                        executionIndex: gitOpsIdx,
                        error: error instanceof Error ? error.message : String(error),
                      });
                      await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
                      await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, true);
                    }
                    throw error;
                  }
                } else {
                  gitOpsIdx = ctx.addExecution('gitOps');
                }

                if (await __ctrl__.beforeNode('notify', ctx)) {

                  // ── notify (weaverSendNotify) ──
                  ctx.checkAborted('notify');
                  notifyIdx = ctx.addExecution('notify');
                  if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'notify';
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverSendNotify',
                    id: 'notify',
                    executionIndex: notifyIdx,
                    status: 'RUNNING',
                  });

                  try {
                    await ctx.setVariable({ id: 'notify', portName: 'execute', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, true);
                    const notify_ctx = await ctx.getVariable({ id: 'execRetry', portName: 'ctx', executionIndex: execRetryIdx! }) as string;
                    await ctx.setVariable({ id: 'notify', portName: 'ctx', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, notify_ctx);
                    const notifyResult = weaverSendNotify(notify_ctx);
                    const notifyResult_raw: unknown = notifyResult;
                    await ctx.setVariable({ id: 'notify', portName: 'ctx', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, typeof notifyResult_raw === 'object' && notifyResult_raw !== null && 'ctx' in notifyResult_raw ? notifyResult_raw.ctx : notifyResult_raw);
                    await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, true);
                    await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
                    await ctx.sendStatusChangedEvent({
                      nodeTypeName: 'weaverSendNotify',
                      id: 'notify',
                      executionIndex: notifyIdx,
                      status: 'SUCCEEDED',
                    });
                    await __ctrl__.afterNode('notify', ctx);
                  } catch (error: unknown) {
                    const isCancellation = CancellationError.isCancellationError(error);
                    await ctx.sendStatusChangedEvent({
                      nodeTypeName: 'weaverSendNotify',
                      id: 'notify',
                      executionIndex: notifyIdx,
                      status: isCancellation ? 'CANCELLED' : 'FAILED',
                    });
                    if (!isCancellation) {
                      ctx.sendLogErrorEvent({
                        nodeTypeName: 'weaverSendNotify',
                        id: 'notify',
                        executionIndex: notifyIdx,
                        error: error instanceof Error ? error.message : String(error),
                      });
                      await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
                      await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, true);
                    }
                    throw error;
                  }
                } else {
                  notifyIdx = ctx.addExecution('notify');
                }

              } else {
                const gitOpsIdx = ctx.addExecution('gitOps');
                await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
                await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverGitOps',
                  id: 'gitOps',
                  executionIndex: gitOpsIdx,
                  status: 'CANCELLED',
                });
                const notifyIdx = ctx.addExecution('notify');
                await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
                await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverSendNotify',
                  id: 'notify',
                  executionIndex: notifyIdx,
                  status: 'CANCELLED',
                });
              }
            } else {
              const execRetryIdx = ctx.addExecution('execRetry');
              await ctx.setVariable({ id: 'execRetry', portName: 'onSuccess', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, false);
              await ctx.setVariable({ id: 'execRetry', portName: 'onFailure', executionIndex: execRetryIdx, nodeTypeName: 'weaverExecValidateRetry' }, false);
              await ctx.sendStatusChangedEvent({
                nodeTypeName: 'weaverExecValidateRetry',
                id: 'execRetry',
                executionIndex: execRetryIdx,
                status: 'CANCELLED',
              });
              if (await __ctrl__.beforeNode('abort', ctx)) {

                // ── abort (weaverAbortTask) ──
                ctx.checkAborted('abort');
                abortIdx = ctx.addExecution('abort');
                if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'abort';
                await ctx.sendStatusChangedEvent({
                  nodeTypeName: 'weaverAbortTask',
                  id: 'abort',
                  executionIndex: abortIdx,
                  status: 'RUNNING',
                });

                try {
                  await ctx.setVariable({ id: 'abort', portName: 'execute', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, true);
                  const abort_ctx = await ctx.getVariable({ id: 'approve', portName: 'ctx', executionIndex: approveIdx! }) as string;
                  await ctx.setVariable({ id: 'abort', portName: 'ctx', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, abort_ctx);
                  const abortResult = weaverAbortTask(abort_ctx);
                  const abortResult_raw: unknown = abortResult;
                  await ctx.setVariable({ id: 'abort', portName: 'ctx', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, typeof abortResult_raw === 'object' && abortResult_raw !== null && 'ctx' in abortResult_raw ? abortResult_raw.ctx : abortResult_raw);
                  await ctx.setVariable({ id: 'abort', portName: 'onSuccess', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, true);
                  await ctx.setVariable({ id: 'abort', portName: 'onFailure', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, false);
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverAbortTask',
                    id: 'abort',
                    executionIndex: abortIdx,
                    status: 'SUCCEEDED',
                  });
                  await __ctrl__.afterNode('abort', ctx);
                } catch (error: unknown) {
                  const isCancellation = CancellationError.isCancellationError(error);
                  await ctx.sendStatusChangedEvent({
                    nodeTypeName: 'weaverAbortTask',
                    id: 'abort',
                    executionIndex: abortIdx,
                    status: isCancellation ? 'CANCELLED' : 'FAILED',
                  });
                  if (!isCancellation) {
                    ctx.sendLogErrorEvent({
                      nodeTypeName: 'weaverAbortTask',
                      id: 'abort',
                      executionIndex: abortIdx,
                      error: error instanceof Error ? error.message : String(error),
                    });
                    await ctx.setVariable({ id: 'abort', portName: 'onSuccess', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, false);
                    await ctx.setVariable({ id: 'abort', portName: 'onFailure', executionIndex: abortIdx, nodeTypeName: 'weaverAbortTask' }, true);
                  }
                  throw error;
                }
              } else {
                abortIdx = ctx.addExecution('abort');
              }

            }
          } else {
            const approveIdx = ctx.addExecution('approve');
            await ctx.setVariable({ id: 'approve', portName: 'onSuccess', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, false);
            await ctx.setVariable({ id: 'approve', portName: 'onFailure', executionIndex: approveIdx, nodeTypeName: 'weaverApprovalGate' }, false);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverApprovalGate',
              id: 'approve',
              executionIndex: approveIdx,
              status: 'CANCELLED',
            });
          }
        } else {
          const planIdx = ctx.addExecution('plan');
          await ctx.setVariable({ id: 'plan', portName: 'onSuccess', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, false);
          await ctx.setVariable({ id: 'plan', portName: 'onFailure', executionIndex: planIdx, nodeTypeName: 'weaverPlanTask' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverPlanTask',
            id: 'plan',
            executionIndex: planIdx,
            status: 'CANCELLED',
          });
        }
      } else {
        const contextIdx = ctx.addExecution('context');
        await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
        await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverBuildContext',
          id: 'context',
          executionIndex: contextIdx,
          status: 'CANCELLED',
        });
        if (await __ctrl__.beforeNode('readWf', ctx)) {

          // ── readWf (weaverReadWorkflow) ──
          ctx.checkAborted('readWf');
          readWfIdx = ctx.addExecution('readWf');
          if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'readWf';
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverReadWorkflow',
            id: 'readWf',
            executionIndex: readWfIdx,
            status: 'RUNNING',
          });

          try {
            await ctx.setVariable({ id: 'readWf', portName: 'execute', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, true);
            const readWf_ctx = await ctx.getVariable({ id: 'route', portName: 'ctx', executionIndex: routeIdx! }) as string;
            await ctx.setVariable({ id: 'readWf', portName: 'ctx', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, readWf_ctx);
            const readWfResult = weaverReadWorkflow(readWf_ctx);
            const readWfResult_raw: unknown = readWfResult;
            await ctx.setVariable({ id: 'readWf', portName: 'ctx', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, typeof readWfResult_raw === 'object' && readWfResult_raw !== null && 'ctx' in readWfResult_raw ? readWfResult_raw.ctx : readWfResult_raw);
            await ctx.setVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, true);
            await ctx.setVariable({ id: 'readWf', portName: 'onFailure', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverReadWorkflow',
              id: 'readWf',
              executionIndex: readWfIdx,
              status: 'SUCCEEDED',
            });
            await __ctrl__.afterNode('readWf', ctx);
          } catch (error: unknown) {
            const isCancellation = CancellationError.isCancellationError(error);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverReadWorkflow',
              id: 'readWf',
              executionIndex: readWfIdx,
              status: isCancellation ? 'CANCELLED' : 'FAILED',
            });
            if (!isCancellation) {
              ctx.sendLogErrorEvent({
                nodeTypeName: 'weaverReadWorkflow',
                id: 'readWf',
                executionIndex: readWfIdx,
                error: error instanceof Error ? error.message : String(error),
              });
              await ctx.setVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
              await ctx.setVariable({ id: 'readWf', portName: 'onFailure', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, true);
            }
            throw error;
          }
        } else {
          readWfIdx = ctx.addExecution('readWf');
        }

      }
    } else {
      const routeIdx = ctx.addExecution('route');
      await ctx.setVariable({ id: 'route', portName: 'onSuccess', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
      await ctx.setVariable({ id: 'route', portName: 'onFailure', executionIndex: routeIdx, nodeTypeName: 'weaverRouteTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverRouteTask',
        id: 'route',
        executionIndex: routeIdx,
        status: 'CANCELLED',
      });
      const contextIdx = ctx.addExecution('context');
      await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBuildContext',
        id: 'context',
        executionIndex: contextIdx,
        status: 'CANCELLED',
      });
      const readWfIdx = ctx.addExecution('readWf');
      await ctx.setVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
      await ctx.setVariable({ id: 'readWf', portName: 'onFailure', executionIndex: readWfIdx, nodeTypeName: 'weaverReadWorkflow' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverReadWorkflow',
        id: 'readWf',
        executionIndex: readWfIdx,
        status: 'CANCELLED',
      });
    }
    if (await __ctrl__.beforeNode('report', ctx)) {

      // ── report (weaverBotReport) ──
      ctx.checkAborted('report');
      reportIdx = ctx.addExecution('report');
      if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'report';
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBotReport',
        id: 'report',
        executionIndex: reportIdx,
        status: 'RUNNING',
      });

      try {
        const report_execute = await ctx.getVariable({ id: 'readWf', portName: 'onSuccess', executionIndex: readWfIdx! }) as boolean;
        await ctx.setVariable({ id: 'report', portName: 'execute', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_execute);
        const report_mainCtx = gitOpsIdx !== undefined ? await ctx.getVariable({ id: 'gitOps', portName: 'ctx', executionIndex: gitOpsIdx }) as string : undefined;
        await ctx.setVariable({ id: 'report', portName: 'mainCtx', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_mainCtx);
        const report_readCtx = readWfIdx !== undefined ? await ctx.getVariable({ id: 'readWf', portName: 'ctx', executionIndex: readWfIdx }) as string : undefined;
        await ctx.setVariable({ id: 'report', portName: 'readCtx', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_readCtx);
        const report_abortCtx = abortIdx !== undefined ? await ctx.getVariable({ id: 'abort', portName: 'ctx', executionIndex: abortIdx }) as string : undefined;
        await ctx.setVariable({ id: 'report', portName: 'abortCtx', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_abortCtx);
        const reportResult = await weaverBotReport(report_execute, report_mainCtx, report_readCtx, report_abortCtx);
        await ctx.setVariable({ id: 'report', portName: 'summary', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.summary);
        await ctx.setVariable({ id: 'report', portName: 'reportJson', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.reportJson);
        await ctx.setVariable({ id: 'report', portName: 'onFailure', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.onFailure);
        await ctx.setVariable({ id: 'report', portName: 'onSuccess', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.onSuccess);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverBotReport',
          id: 'report',
          executionIndex: reportIdx,
          status: 'SUCCEEDED',
        });
        await __ctrl__.afterNode('report', ctx);
      } catch (error: unknown) {
        const isCancellation = CancellationError.isCancellationError(error);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverBotReport',
          id: 'report',
          executionIndex: reportIdx,
          status: isCancellation ? 'CANCELLED' : 'FAILED',
        });
        if (!isCancellation) {
          ctx.sendLogErrorEvent({
            nodeTypeName: 'weaverBotReport',
            id: 'report',
            executionIndex: reportIdx,
            error: error instanceof Error ? error.message : String(error),
          });
          await ctx.setVariable({ id: 'report', portName: 'onSuccess', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, false);
          await ctx.setVariable({ id: 'report', portName: 'onFailure', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, true);
        }
        throw error;
      }
    } else {
      reportIdx = ctx.addExecution('report');
    }

    const exitIdx = ctx.addExecution('Exit');
    const exit_summary = reportIdx !== undefined ? await ctx.getVariable({ id: 'report', portName: 'summary', executionIndex: reportIdx }) : undefined;
    await ctx.setVariable({ id: 'Exit', portName: 'summary', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_summary);
    const exit_onSuccess = reportIdx !== undefined ? await ctx.getVariable({ id: 'report', portName: 'onSuccess', executionIndex: reportIdx }) : false;
    await ctx.setVariable({ id: 'Exit', portName: 'onSuccess', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_onSuccess);

    await ctx.setVariable({ id: 'Exit', portName: 'onFailure', executionIndex: exitIdx, nodeTypeName: 'Exit' }, false);
    const finalResult = { onFailure: false, summary: exit_summary as string, onSuccess: exit_onSuccess as boolean };

    await ctx.sendStatusChangedEvent({
      nodeTypeName: 'Exit',
      id: 'Exit',
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
    });
    ctx.sendWorkflowCompletedEvent({
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
      result: finalResult,
    });

    return finalResult;
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
