// Managed weaver bot batch workflow - processes multiple tasks via forEach scope.
// Run `weaver eject` to customize.

import { weaverLoadConfig } from '../node-types/load-config.js';
import { weaverDetectProvider } from '../node-types/detect-provider.js';
import { weaverReceiveTask } from '../node-types/receive-task.js';
import { weaverBuildContext } from '../node-types/build-context.js';
import { weaverPlanTask } from '../node-types/plan-task.js';
import { weaverApprovalGate } from '../node-types/approval-gate.js';
import { weaverAbortTask } from '../node-types/abort-task.js';
import { weaverExecValidateRetry } from '../node-types/exec-validate-retry.js';
import { weaverGitOps } from '../node-types/git-ops.js';
import { weaverSendNotify } from '../node-types/send-notify.js';
import { weaverBotReport } from '../node-types/bot-report.js';

/**
 * Batch workflow bot. Processes multiple sub-tasks sequentially,
 * running the full plan-approve-execute cycle for each.
 *
 * @flowWeaver workflow
 *
 * @node cfg       weaverLoadConfig       [color: "teal"]    [icon: "settings"]      [position: 80 200]
 * @node detect    weaverDetectProvider   [color: "cyan"]    [icon: "search"]        [position: 230 200]
 * @node receive   weaverReceiveTask      [color: "blue"]    [icon: "send"]          [position: 380 200]
 * @node context   weaverBuildContext     [color: "teal"]    [icon: "code"]          [position: 530 200]
 * @node plan      weaverPlanTask         [color: "blue"]    [icon: "psychology"]    [position: 680 200]
 * @node approve   weaverApprovalGate     [color: "orange"]  [icon: "send"]          [position: 830 200]
 * @node abort     weaverAbortTask        [color: "red"]     [icon: "code"]          [position: 980 400]
 * @node execRetry weaverExecValidateRetry [color: "purple"] [icon: "code"]          [position: 980 200]
 * @node gitOps    weaverGitOps           [color: "green"]   [icon: "code"]          [position: 1130 100]
 * @node notify    weaverSendNotify       [color: "yellow"]  [icon: "send"]          [position: 1130 300]
 * @node report    weaverBotReport        [color: "green"]   [icon: "description"]   [position: 1300 200]
 *
 * @path Start -> cfg -> detect -> receive -> context -> plan -> approve -> execRetry -> gitOps -> report -> Exit
 * @path execRetry -> notify
 * @path approve:fail -> abort
 *
 * @connect notify.onSuccess -> report.execute
 * @connect abort.onSuccess -> report.execute
 *
 * @connect context.contextBundle -> plan.contextBundle
 *
 * @connect approve.rejectionReason -> abort.rejectionReason
 * @connect approve.taskJson -> abort.taskJson
 * @connect abort.resultJson -> report.abortResult
 *
 * @connect execRetry.resultJson -> notify.resultJson
 *
 * @connect execRetry.resultJson -> report.mainResult
 * @connect execRetry.filesModified -> report.filesModified
 * @connect gitOps.gitResultJson -> report.gitResultJson
 *
 * @connect report.summary -> Exit.summary
 *
 * @position Start 0 200
 * @position Exit 1450 200
 *
 * @param execute [order:-1] - Execute
 * @param taskJson [order:0] [optional] - Batch task instruction (JSON)
 * @param projectDir [order:1] [optional] - Project directory
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaverBotBatch(
  execute: boolean,
  taskJson?: string,
  projectDir?: string,
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // (auto-generated by compiler)
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
