// Managed weaver bot session workflow - continuously processes task queue.
// Run `weaver eject` to customize.

import { weaverLoadConfig } from '../node-types/load-config.js';
import { weaverDetectProvider } from '../node-types/detect-provider.js';
import { weaverReceiveTask } from '../node-types/receive-task.js';
import { weaverRouteTask } from '../node-types/route-task.js';
import { weaverReadWorkflow } from '../node-types/read-workflow.js';
import { weaverBuildContext } from '../node-types/build-context.js';
import { weaverPlanTask } from '../node-types/plan-task.js';
import { weaverApprovalGate } from '../node-types/approval-gate.js';
import { weaverAbortTask } from '../node-types/abort-task.js';
import { weaverExecValidateRetry } from '../node-types/exec-validate-retry.js';
import { weaverGitOps } from '../node-types/git-ops.js';
import { weaverSendNotify } from '../node-types/send-notify.js';
import { weaverBotReport } from '../node-types/bot-report.js';

/**
 * Session mode bot. Continuously polls the task queue and processes
 * tasks through the full bot pipeline.
 *
 * @flowWeaver workflow
 *
 * @node cfg      weaverLoadConfig       [color: "teal"]    [icon: "settings"]      [position: 80 200]
 * @node detect   weaverDetectProvider   [color: "cyan"]    [icon: "search"]        [position: 230 200]
 * @node receive  weaverReceiveTask      [color: "blue"]    [icon: "send"]          [position: 400 200]
 * @node route    weaverRouteTask        [color: "purple"]  [icon: "flow"]          [position: 570 200]
 * @node readWf   weaverReadWorkflow     [color: "cyan"]    [icon: "description"]   [position: 740 450]
 * @node context  weaverBuildContext     [color: "teal"]    [icon: "code"]          [position: 740 200]
 * @node plan     weaverPlanTask         [color: "blue"]    [icon: "psychology"]    [position: 910 200]
 * @node approve  weaverApprovalGate     [color: "orange"]  [icon: "send"]          [position: 1080 200]
 * @node abort    weaverAbortTask        [color: "red"]     [icon: "code"]          [position: 1250 450]
 * @node execRetry weaverExecValidateRetry [color: "purple"] [icon: "code"]         [position: 1250 200]
 * @node gitOps   weaverGitOps           [color: "green"]   [icon: "code"]          [position: 1420 100]
 * @node notify   weaverSendNotify       [color: "yellow"]  [icon: "send"]          [position: 1420 300]
 * @node report   weaverBotReport        [color: "green"]   [icon: "description"]   [position: 1600 200]
 *
 * @path Start -> cfg -> detect -> receive -> route -> context -> plan -> approve -> execRetry -> gitOps -> report -> Exit
 * @path execRetry -> notify
 * @path route:fail -> readWf
 * @path approve:fail -> abort
 *
 * @connect readWf.onSuccess -> report.execute
 * @connect abort.onSuccess -> report.execute
 * @connect notify.onSuccess -> report.execute
 *
 * @connect route.taskJson -> readWf.taskJson
 * @connect route.projectDir -> readWf.projectDir
 * @connect readWf.resultJson -> report.readResult
 *
 * @connect context.contextBundle -> plan.contextBundle
 *
 * @connect approve.rejectionReason -> abort.rejectionReason
 * @connect approve.taskJson -> abort.taskJson
 * @connect approve.projectDir -> abort.projectDir
 * @connect abort.resultJson -> report.abortResult
 *
 * @connect execRetry.resultJson -> notify.resultJson
 * @connect execRetry.projectDir -> notify.targetPath
 *
 * @connect execRetry.resultJson -> report.mainResult
 * @connect execRetry.filesModified -> report.filesModified
 * @connect gitOps.gitResultJson -> report.gitResultJson
 *
 * @connect report.summary -> Exit.summary
 *
 * @position Start 0 200
 * @position Exit 1750 200
 *
 * @param execute [order:-1] - Execute
 * @param taskJson [order:0] [optional] - Task instruction (JSON)
 * @param projectDir [order:1] [optional] - Project directory
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaverBotSession(
  execute: boolean,
  taskJson?: string,
  projectDir?: string,
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // (auto-generated by compiler)
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
