// Managed weaver workflow - shipped with the pack.
// Users on managed mode use this automatically.
// Run `weaver eject` to customize.

import { weaverLoadConfig } from '../node-types/load-config.js';
import { weaverDetectProvider } from '../node-types/detect-provider.js';
import { weaverResolveTarget } from '../node-types/resolve-target.js';
import { weaverExecuteTarget } from '../node-types/execute-target.js';
import { weaverSendNotify } from '../node-types/send-notify.js';
import { weaverReport } from '../node-types/report.js';

/**
 * @flowWeaver workflow
 * @node cfg weaverLoadConfig [color: "teal"] [icon: "settings"] [position: 200 0]
 * @node detect weaverDetectProvider [color: "cyan"] [icon: "search"] [position: 400 0]
 * @node target weaverResolveTarget [color: "blue"] [icon: "code"] [position: 600 0]
 * @node exec weaverExecuteTarget [color: "purple"] [icon: "psychology"] [position: 800 0]
 * @node notify weaverSendNotify [color: "yellow"] [icon: "notifications"] [position: 1000 0]
 * @node rep weaverReport [color: "green"] [icon: "description"] [position: 1200 0]
 * @path Start -> cfg -> detect -> target -> exec -> notify -> rep -> Exit
 * @position Start 0 0
 * @position Exit 1400 0
 * @connect rep.summary -> Exit.summary
 * @param execute [order:-1] - Execute
 * @param params [order:0] [hidden] - Params
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] [hidden] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaver(
  execute: boolean,
  params: Record<string, never> = {},
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // (auto-generated by compiler)
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
