// Weaver agent workflow — tool-use based execution.
// Uses Claude's tool calling to drive tasks dynamically instead of
// the plan-execute-retry pattern.

import { weaverLoadConfig } from '../node-types/load-config.js';
import { weaverDetectProvider } from '../node-types/detect-provider.js';
import { weaverReceiveTask } from '../node-types/receive-task.js';
import { weaverBuildContext } from '../node-types/build-context.js';
import { weaverAgentExecute } from '../node-types/agent-execute.js';
import { weaverGitOps } from '../node-types/git-ops.js';
import { weaverSendNotify } from '../node-types/send-notify.js';
import { weaverBotReport } from '../node-types/bot-report.js';

// @flow-weaver-runtime-start
// ============================================================================
// DO NOT EDIT - This section is auto-generated by Flow Weaver
// ============================================================================

import { GeneratedExecutionContext, CancellationError } from '@synergenius/flow-weaver/runtime';
import type { TDebugger, TDebugController } from '@synergenius/flow-weaver/runtime';
declare const __flowWeaverDebugger__: TDebugger | undefined;
// @flow-weaver-runtime-end

/**
 * @flowWeaver workflow
 * @node cfg weaverLoadConfig [color: "teal"] [icon: "settings"] [position: 200 200]
 * @node detect weaverDetectProvider [color: "cyan"] [icon: "search"] [position: 400 200]
 * @node receive weaverReceiveTask [color: "blue"] [icon: "send"] [position: 600 200]
 * @node context weaverBuildContext [color: "teal"] [icon: "code"] [position: 800 200]
 * @node agent weaverAgentExecute [color: "purple"] [icon: "psychology"] [position: 1000 200]
 * @node gitOps weaverGitOps [color: "green"] [icon: "code"] [position: 1200 100]
 * @node notify weaverSendNotify [color: "yellow"] [icon: "send"] [position: 1200 300]
 * @node report weaverBotReport [color: "green"] [icon: "description"] [position: 1400 200]
 * @path Start -> cfg -> detect -> receive -> context -> agent -> gitOps -> report -> Exit
 * @path agent -> notify
 * @position Start 0 200
 * @position Exit 1600 200
 * @connect gitOps.ctx -> report.mainCtx
 * @connect notify.onSuccess -> report.execute
 * @connect report.summary -> Exit.summary
 * @param execute [order:-1] - Execute
 * @param taskJson [order:0] - TaskJson
 * @param projectDir [order:1] - ProjectDir
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaverAgent(
  execute: boolean,
  params: { taskJson?: string; projectDir?: string },
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // ============================================================================
  // DO NOT EDIT - This section is auto-generated by Flow Weaver
  // Edit the @flowWeaver annotations above to modify workflow behavior
  // ============================================================================

    const __effectiveDebugger__ = typeof __flowWeaverDebugger__ !== 'undefined' ? __flowWeaverDebugger__ : undefined;

    // Recursion depth protection
    const __rd__ = (params as { __rd__?: number }).__rd__ ?? 0;
    if (__rd__ >= 1000) {
      throw new Error('Max recursion depth exceeded (1000) in workflow "weaverAgent"');
    }

    const ctx = new GeneratedExecutionContext(true, __effectiveDebugger__, __abortSignal__);

    // Debug controller for step-through debugging and checkpoint/resume
    const __ctrl__: TDebugController = (
      typeof globalThis !== 'undefined' && (globalThis as unknown as { __fw_debug_controller__?: TDebugController }).__fw_debug_controller__
        ? (globalThis as unknown as { __fw_debug_controller__?: TDebugController }).__fw_debug_controller__
        : { beforeNode: () => true, afterNode: () => {} }
    )!;

    const startIdx = ctx.addExecution('Start');
    await ctx.setVariable({ id: 'Start', portName: 'execute', executionIndex: startIdx, nodeTypeName: 'Start' }, execute);
    await ctx.setVariable({ id: 'Start', portName: 'taskJson', executionIndex: startIdx, nodeTypeName: 'Start' }, params.taskJson);
    await ctx.setVariable({ id: 'Start', portName: 'projectDir', executionIndex: startIdx, nodeTypeName: 'Start' }, params.projectDir);
    await ctx.sendStatusChangedEvent({
      nodeTypeName: 'Start',
      id: 'Start',
      executionIndex: startIdx,
      status: 'SUCCEEDED',
    });

    let cfgIdx: number | undefined;
    let detectIdx: number | undefined;
    let receiveIdx: number | undefined;
    let contextIdx: number | undefined;
    let agentIdx: number | undefined;
    let gitOpsIdx: number | undefined;
    let notifyIdx: number | undefined;
    let reportIdx: number | undefined;

    let cfg_success = false;
    let detect_success = false;
    let receive_success = false;
    let context_success = false;

    if (await __ctrl__.beforeNode('cfg', ctx)) {

      // ── cfg (weaverLoadConfig) ──
      ctx.checkAborted('cfg');
      cfgIdx = ctx.addExecution('cfg');
      if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'cfg';
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverLoadConfig',
        id: 'cfg',
        executionIndex: cfgIdx,
        status: 'RUNNING',
      });

      cfg_success = false;

      try {
        await ctx.setVariable({ id: 'cfg', portName: 'execute', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, true);
        const cfg_projectDir = await ctx.getVariable({ id: 'Start', portName: 'projectDir', executionIndex: startIdx }) as string;
        await ctx.setVariable({ id: 'cfg', portName: 'projectDir', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, cfg_projectDir);
        const cfgResult = weaverLoadConfig(cfg_projectDir);
        await ctx.setVariable({ id: 'cfg', portName: 'projectDir', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, cfgResult.projectDir);
        await ctx.setVariable({ id: 'cfg', portName: 'config', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, cfgResult.config);
        await ctx.setVariable({ id: 'cfg', portName: 'onSuccess', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, true);
        await ctx.setVariable({ id: 'cfg', portName: 'onFailure', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverLoadConfig',
          id: 'cfg',
          executionIndex: cfgIdx,
          status: 'SUCCEEDED',
        });
        await __ctrl__.afterNode('cfg', ctx);
        cfg_success = true;
      } catch (error: unknown) {
        const isCancellation = CancellationError.isCancellationError(error);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverLoadConfig',
          id: 'cfg',
          executionIndex: cfgIdx,
          status: isCancellation ? 'CANCELLED' : 'FAILED',
        });
        if (!isCancellation) {
          ctx.sendLogErrorEvent({
            nodeTypeName: 'weaverLoadConfig',
            id: 'cfg',
            executionIndex: cfgIdx,
            error: error instanceof Error ? error.message : String(error),
          });
          await ctx.setVariable({ id: 'cfg', portName: 'onSuccess', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, false);
          await ctx.setVariable({ id: 'cfg', portName: 'onFailure', executionIndex: cfgIdx, nodeTypeName: 'weaverLoadConfig' }, true);
          cfg_success = false;
        }
        throw error;
      }
    } else {
      cfgIdx = ctx.addExecution('cfg');
      cfg_success = true;
    }

    if (cfg_success) {
      if (await __ctrl__.beforeNode('detect', ctx)) {

        // ── detect (weaverDetectProvider) ──
        ctx.checkAborted('detect');
        detectIdx = ctx.addExecution('detect');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'detect';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverDetectProvider',
          id: 'detect',
          executionIndex: detectIdx,
          status: 'RUNNING',
        });

        detect_success = false;

        try {
          await ctx.setVariable({ id: 'detect', portName: 'execute', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, true);
          const detect_projectDir = await ctx.getVariable({ id: 'cfg', portName: 'projectDir', executionIndex: cfgIdx! }) as string;
          await ctx.setVariable({ id: 'detect', portName: 'projectDir', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, detect_projectDir);
          const detect_config = await ctx.getVariable({ id: 'cfg', portName: 'config', executionIndex: cfgIdx! }) as Parameters<typeof weaverDetectProvider>[1];
          await ctx.setVariable({ id: 'detect', portName: 'config', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, detect_config);
          const detectResult = weaverDetectProvider(detect_projectDir, detect_config);
          const detectResult_raw: unknown = detectResult;
          await ctx.setVariable({ id: 'detect', portName: 'env', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, typeof detectResult_raw === 'object' && detectResult_raw !== null && 'env' in detectResult_raw ? detectResult_raw.env : detectResult_raw);
          await ctx.setVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, true);
          await ctx.setVariable({ id: 'detect', portName: 'onFailure', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverDetectProvider',
            id: 'detect',
            executionIndex: detectIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('detect', ctx);
          detect_success = true;
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverDetectProvider',
            id: 'detect',
            executionIndex: detectIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'weaverDetectProvider',
              id: 'detect',
              executionIndex: detectIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
            await ctx.setVariable({ id: 'detect', portName: 'onFailure', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, true);
            detect_success = false;
          }
          throw error;
        }
      } else {
        detectIdx = ctx.addExecution('detect');
        detect_success = true;
      }

    } else {
      const detectIdx = ctx.addExecution('detect');
      await ctx.setVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
      await ctx.setVariable({ id: 'detect', portName: 'onFailure', executionIndex: detectIdx, nodeTypeName: 'weaverDetectProvider' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverDetectProvider',
        id: 'detect',
        executionIndex: detectIdx,
        status: 'CANCELLED',
      });
      const receiveIdx = ctx.addExecution('receive');
      await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverReceiveTask',
        id: 'receive',
        executionIndex: receiveIdx,
        status: 'CANCELLED',
      });
      const contextIdx = ctx.addExecution('context');
      await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBuildContext',
        id: 'context',
        executionIndex: contextIdx,
        status: 'CANCELLED',
      });
      const agentIdx = ctx.addExecution('agent');
      await ctx.setVariable({ id: 'agent', portName: 'onSuccess', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.setVariable({ id: 'agent', portName: 'onFailure', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverAgentExecute',
        id: 'agent',
        executionIndex: agentIdx,
        status: 'CANCELLED',
      });
      const gitOpsIdx = ctx.addExecution('gitOps');
      await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverGitOps',
        id: 'gitOps',
        executionIndex: gitOpsIdx,
        status: 'CANCELLED',
      });
      const notifyIdx = ctx.addExecution('notify');
      await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverSendNotify',
        id: 'notify',
        executionIndex: notifyIdx,
        status: 'CANCELLED',
      });
    }
    if (cfg_success && detect_success) {
      if (await __ctrl__.beforeNode('receive', ctx)) {

        // ── receive (weaverReceiveTask) ──
        ctx.checkAborted('receive');
        receiveIdx = ctx.addExecution('receive');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'receive';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverReceiveTask',
          id: 'receive',
          executionIndex: receiveIdx,
          status: 'RUNNING',
        });

        receive_success = false;

        try {
          const receive_execute = detectIdx !== undefined ? await ctx.getVariable({ id: 'detect', portName: 'onSuccess', executionIndex: detectIdx }) as boolean : false;
          await ctx.setVariable({ id: 'receive', portName: 'execute', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receive_execute);
          const receive_env = await ctx.getVariable({ id: 'detect', portName: 'env', executionIndex: detectIdx! }) as Parameters<typeof weaverReceiveTask>[1];
          await ctx.setVariable({ id: 'receive', portName: 'env', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receive_env);
          const receive_taskJson = await ctx.getVariable({ id: 'Start', portName: 'taskJson', executionIndex: startIdx }) as string;
          await ctx.setVariable({ id: 'receive', portName: 'taskJson', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receive_taskJson);
          const receiveResult = await weaverReceiveTask(receive_execute, receive_env, receive_taskJson);
          await ctx.setVariable({ id: 'receive', portName: 'ctx', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receiveResult.ctx);
          await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receiveResult.onSuccess);
          await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, receiveResult.onFailure);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverReceiveTask',
            id: 'receive',
            executionIndex: receiveIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('receive', ctx);
          receive_success = receiveResult.onSuccess;
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverReceiveTask',
            id: 'receive',
            executionIndex: receiveIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'weaverReceiveTask',
              id: 'receive',
              executionIndex: receiveIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
            await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, true);
            receive_success = false;
          }
          throw error;
        }
      } else {
        receiveIdx = ctx.addExecution('receive');
        receive_success = true;
      }

    } else {
      const receiveIdx = ctx.addExecution('receive');
      await ctx.setVariable({ id: 'receive', portName: 'onSuccess', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.setVariable({ id: 'receive', portName: 'onFailure', executionIndex: receiveIdx, nodeTypeName: 'weaverReceiveTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverReceiveTask',
        id: 'receive',
        executionIndex: receiveIdx,
        status: 'CANCELLED',
      });
      const contextIdx = ctx.addExecution('context');
      await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBuildContext',
        id: 'context',
        executionIndex: contextIdx,
        status: 'CANCELLED',
      });
      const agentIdx = ctx.addExecution('agent');
      await ctx.setVariable({ id: 'agent', portName: 'onSuccess', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.setVariable({ id: 'agent', portName: 'onFailure', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverAgentExecute',
        id: 'agent',
        executionIndex: agentIdx,
        status: 'CANCELLED',
      });
      const gitOpsIdx = ctx.addExecution('gitOps');
      await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverGitOps',
        id: 'gitOps',
        executionIndex: gitOpsIdx,
        status: 'CANCELLED',
      });
      const notifyIdx = ctx.addExecution('notify');
      await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverSendNotify',
        id: 'notify',
        executionIndex: notifyIdx,
        status: 'CANCELLED',
      });
    }
    if (cfg_success && detect_success && receive_success) {
      if (await __ctrl__.beforeNode('context', ctx)) {

        // ── context (weaverBuildContext) ──
        ctx.checkAborted('context');
        contextIdx = ctx.addExecution('context');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'context';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverBuildContext',
          id: 'context',
          executionIndex: contextIdx,
          status: 'RUNNING',
        });

        context_success = false;

        try {
          await ctx.setVariable({ id: 'context', portName: 'execute', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, true);
          const context_ctx = await ctx.getVariable({ id: 'receive', portName: 'ctx', executionIndex: receiveIdx! }) as string;
          await ctx.setVariable({ id: 'context', portName: 'ctx', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, context_ctx);
          const contextResult = weaverBuildContext(context_ctx);
          const contextResult_raw: unknown = contextResult;
          await ctx.setVariable({ id: 'context', portName: 'ctx', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, typeof contextResult_raw === 'object' && contextResult_raw !== null && 'ctx' in contextResult_raw ? contextResult_raw.ctx : contextResult_raw);
          await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, true);
          await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverBuildContext',
            id: 'context',
            executionIndex: contextIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('context', ctx);
          context_success = true;
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverBuildContext',
            id: 'context',
            executionIndex: contextIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'weaverBuildContext',
              id: 'context',
              executionIndex: contextIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
            await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, true);
            context_success = false;
          }
          throw error;
        }
      } else {
        contextIdx = ctx.addExecution('context');
        context_success = true;
      }

    } else {
      const contextIdx = ctx.addExecution('context');
      await ctx.setVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.setVariable({ id: 'context', portName: 'onFailure', executionIndex: contextIdx, nodeTypeName: 'weaverBuildContext' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBuildContext',
        id: 'context',
        executionIndex: contextIdx,
        status: 'CANCELLED',
      });
      const agentIdx = ctx.addExecution('agent');
      await ctx.setVariable({ id: 'agent', portName: 'onSuccess', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.setVariable({ id: 'agent', portName: 'onFailure', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverAgentExecute',
        id: 'agent',
        executionIndex: agentIdx,
        status: 'CANCELLED',
      });
      const gitOpsIdx = ctx.addExecution('gitOps');
      await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverGitOps',
        id: 'gitOps',
        executionIndex: gitOpsIdx,
        status: 'CANCELLED',
      });
      const notifyIdx = ctx.addExecution('notify');
      await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverSendNotify',
        id: 'notify',
        executionIndex: notifyIdx,
        status: 'CANCELLED',
      });
    }
    if (cfg_success && detect_success && receive_success && context_success) {
      let agent_success = false;
      if (await __ctrl__.beforeNode('agent', ctx)) {

        // ── agent (weaverAgentExecute) ──
        ctx.checkAborted('agent');
        agentIdx = ctx.addExecution('agent');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'agent';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverAgentExecute',
          id: 'agent',
          executionIndex: agentIdx,
          status: 'RUNNING',
        });

        agent_success = false;

        try {
          const agent_execute = contextIdx !== undefined ? await ctx.getVariable({ id: 'context', portName: 'onSuccess', executionIndex: contextIdx }) as boolean : false;
          await ctx.setVariable({ id: 'agent', portName: 'execute', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, agent_execute);
          const agent_ctx = await ctx.getVariable({ id: 'context', portName: 'ctx', executionIndex: contextIdx! }) as string;
          await ctx.setVariable({ id: 'agent', portName: 'ctx', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, agent_ctx);
          const agentResult = await weaverAgentExecute(agent_execute, agent_ctx);
          await ctx.setVariable({ id: 'agent', portName: 'ctx', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, agentResult.ctx);
          await ctx.setVariable({ id: 'agent', portName: 'onSuccess', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, agentResult.onSuccess);
          await ctx.setVariable({ id: 'agent', portName: 'onFailure', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, agentResult.onFailure);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverAgentExecute',
            id: 'agent',
            executionIndex: agentIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('agent', ctx);
          agent_success = agentResult.onSuccess;
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverAgentExecute',
            id: 'agent',
            executionIndex: agentIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'weaverAgentExecute',
              id: 'agent',
              executionIndex: agentIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'agent', portName: 'onSuccess', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
            await ctx.setVariable({ id: 'agent', portName: 'onFailure', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, true);
            agent_success = false;
          }
          const gitOpsIdx = ctx.addExecution('gitOps');
          await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
          await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverGitOps',
            id: 'gitOps',
            executionIndex: gitOpsIdx,
            status: 'CANCELLED',
          });
          const notifyIdx = ctx.addExecution('notify');
          await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
          await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverSendNotify',
            id: 'notify',
            executionIndex: notifyIdx,
            status: 'CANCELLED',
          });
          throw error;
        }
      } else {
        agentIdx = ctx.addExecution('agent');
        agent_success = true;
      }

      if (agent_success) {
        if (await __ctrl__.beforeNode('gitOps', ctx)) {

          // ── gitOps (weaverGitOps) ──
          ctx.checkAborted('gitOps');
          gitOpsIdx = ctx.addExecution('gitOps');
          if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'gitOps';
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverGitOps',
            id: 'gitOps',
            executionIndex: gitOpsIdx,
            status: 'RUNNING',
          });

          try {
            await ctx.setVariable({ id: 'gitOps', portName: 'execute', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, true);
            const gitOps_ctx = await ctx.getVariable({ id: 'agent', portName: 'ctx', executionIndex: agentIdx! }) as string;
            await ctx.setVariable({ id: 'gitOps', portName: 'ctx', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, gitOps_ctx);
            const gitOpsResult = weaverGitOps(gitOps_ctx);
            const gitOpsResult_raw: unknown = gitOpsResult;
            await ctx.setVariable({ id: 'gitOps', portName: 'ctx', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, typeof gitOpsResult_raw === 'object' && gitOpsResult_raw !== null && 'ctx' in gitOpsResult_raw ? gitOpsResult_raw.ctx : gitOpsResult_raw);
            await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, true);
            await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverGitOps',
              id: 'gitOps',
              executionIndex: gitOpsIdx,
              status: 'SUCCEEDED',
            });
            await __ctrl__.afterNode('gitOps', ctx);
          } catch (error: unknown) {
            const isCancellation = CancellationError.isCancellationError(error);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverGitOps',
              id: 'gitOps',
              executionIndex: gitOpsIdx,
              status: isCancellation ? 'CANCELLED' : 'FAILED',
            });
            if (!isCancellation) {
              ctx.sendLogErrorEvent({
                nodeTypeName: 'weaverGitOps',
                id: 'gitOps',
                executionIndex: gitOpsIdx,
                error: error instanceof Error ? error.message : String(error),
              });
              await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
              await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, true);
            }
            throw error;
          }
        } else {
          gitOpsIdx = ctx.addExecution('gitOps');
        }

        if (await __ctrl__.beforeNode('notify', ctx)) {

          // ── notify (weaverSendNotify) ──
          ctx.checkAborted('notify');
          notifyIdx = ctx.addExecution('notify');
          if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'notify';
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'weaverSendNotify',
            id: 'notify',
            executionIndex: notifyIdx,
            status: 'RUNNING',
          });

          try {
            await ctx.setVariable({ id: 'notify', portName: 'execute', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, true);
            const notify_ctx = await ctx.getVariable({ id: 'agent', portName: 'ctx', executionIndex: agentIdx! }) as string;
            await ctx.setVariable({ id: 'notify', portName: 'ctx', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, notify_ctx);
            const notifyResult = weaverSendNotify(notify_ctx);
            const notifyResult_raw: unknown = notifyResult;
            await ctx.setVariable({ id: 'notify', portName: 'ctx', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, typeof notifyResult_raw === 'object' && notifyResult_raw !== null && 'ctx' in notifyResult_raw ? notifyResult_raw.ctx : notifyResult_raw);
            await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, true);
            await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverSendNotify',
              id: 'notify',
              executionIndex: notifyIdx,
              status: 'SUCCEEDED',
            });
            await __ctrl__.afterNode('notify', ctx);
          } catch (error: unknown) {
            const isCancellation = CancellationError.isCancellationError(error);
            await ctx.sendStatusChangedEvent({
              nodeTypeName: 'weaverSendNotify',
              id: 'notify',
              executionIndex: notifyIdx,
              status: isCancellation ? 'CANCELLED' : 'FAILED',
            });
            if (!isCancellation) {
              ctx.sendLogErrorEvent({
                nodeTypeName: 'weaverSendNotify',
                id: 'notify',
                executionIndex: notifyIdx,
                error: error instanceof Error ? error.message : String(error),
              });
              await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
              await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, true);
            }
            throw error;
          }
        } else {
          notifyIdx = ctx.addExecution('notify');
        }

      } else {
        const gitOpsIdx = ctx.addExecution('gitOps');
        await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
        await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverGitOps',
          id: 'gitOps',
          executionIndex: gitOpsIdx,
          status: 'CANCELLED',
        });
        const notifyIdx = ctx.addExecution('notify');
        await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
        await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverSendNotify',
          id: 'notify',
          executionIndex: notifyIdx,
          status: 'CANCELLED',
        });
      }
    } else {
      const agentIdx = ctx.addExecution('agent');
      await ctx.setVariable({ id: 'agent', portName: 'onSuccess', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.setVariable({ id: 'agent', portName: 'onFailure', executionIndex: agentIdx, nodeTypeName: 'weaverAgentExecute' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverAgentExecute',
        id: 'agent',
        executionIndex: agentIdx,
        status: 'CANCELLED',
      });
      const gitOpsIdx = ctx.addExecution('gitOps');
      await ctx.setVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.setVariable({ id: 'gitOps', portName: 'onFailure', executionIndex: gitOpsIdx, nodeTypeName: 'weaverGitOps' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverGitOps',
        id: 'gitOps',
        executionIndex: gitOpsIdx,
        status: 'CANCELLED',
      });
      const notifyIdx = ctx.addExecution('notify');
      await ctx.setVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.setVariable({ id: 'notify', portName: 'onFailure', executionIndex: notifyIdx, nodeTypeName: 'weaverSendNotify' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverSendNotify',
        id: 'notify',
        executionIndex: notifyIdx,
        status: 'CANCELLED',
      });
    }
    if (await __ctrl__.beforeNode('report', ctx)) {

      // ── report (weaverBotReport) ──
      ctx.checkAborted('report');
      reportIdx = ctx.addExecution('report');
      if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'report';
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'weaverBotReport',
        id: 'report',
        executionIndex: reportIdx,
        status: 'RUNNING',
      });

      try {
        const report_execute = (notifyIdx !== undefined ? await ctx.getVariable({ id: 'notify', portName: 'onSuccess', executionIndex: notifyIdx }) as boolean : false) || (gitOpsIdx !== undefined ? await ctx.getVariable({ id: 'gitOps', portName: 'onSuccess', executionIndex: gitOpsIdx }) as boolean : false);
        await ctx.setVariable({ id: 'report', portName: 'execute', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_execute);
        const report_mainCtx = gitOpsIdx !== undefined ? await ctx.getVariable({ id: 'gitOps', portName: 'ctx', executionIndex: gitOpsIdx }) as string : undefined;
        await ctx.setVariable({ id: 'report', portName: 'mainCtx', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_mainCtx);
        const report_readCtx = undefined;
        await ctx.setVariable({ id: 'report', portName: 'readCtx', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_readCtx);
        const report_abortCtx = undefined;
        await ctx.setVariable({ id: 'report', portName: 'abortCtx', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, report_abortCtx);
        const reportResult = await weaverBotReport(report_execute, report_mainCtx, report_readCtx, report_abortCtx);
        await ctx.setVariable({ id: 'report', portName: 'summary', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.summary);
        await ctx.setVariable({ id: 'report', portName: 'reportJson', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.reportJson);
        await ctx.setVariable({ id: 'report', portName: 'onFailure', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.onFailure);
        await ctx.setVariable({ id: 'report', portName: 'onSuccess', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, reportResult.onSuccess);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverBotReport',
          id: 'report',
          executionIndex: reportIdx,
          status: 'SUCCEEDED',
        });
        await __ctrl__.afterNode('report', ctx);
      } catch (error: unknown) {
        const isCancellation = CancellationError.isCancellationError(error);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'weaverBotReport',
          id: 'report',
          executionIndex: reportIdx,
          status: isCancellation ? 'CANCELLED' : 'FAILED',
        });
        if (!isCancellation) {
          ctx.sendLogErrorEvent({
            nodeTypeName: 'weaverBotReport',
            id: 'report',
            executionIndex: reportIdx,
            error: error instanceof Error ? error.message : String(error),
          });
          await ctx.setVariable({ id: 'report', portName: 'onSuccess', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, false);
          await ctx.setVariable({ id: 'report', portName: 'onFailure', executionIndex: reportIdx, nodeTypeName: 'weaverBotReport' }, true);
        }
        throw error;
      }
    } else {
      reportIdx = ctx.addExecution('report');
    }

    const exitIdx = ctx.addExecution('Exit');
    const exit_summary = reportIdx !== undefined ? await ctx.getVariable({ id: 'report', portName: 'summary', executionIndex: reportIdx }) : undefined;
    await ctx.setVariable({ id: 'Exit', portName: 'summary', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_summary);
    const exit_onSuccess = reportIdx !== undefined ? await ctx.getVariable({ id: 'report', portName: 'onSuccess', executionIndex: reportIdx }) : false;
    await ctx.setVariable({ id: 'Exit', portName: 'onSuccess', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_onSuccess);

    await ctx.setVariable({ id: 'Exit', portName: 'onFailure', executionIndex: exitIdx, nodeTypeName: 'Exit' }, false);
    const finalResult = { onFailure: false, summary: exit_summary as string, onSuccess: exit_onSuccess as boolean };

    await ctx.sendStatusChangedEvent({
      nodeTypeName: 'Exit',
      id: 'Exit',
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
    });
    ctx.sendWorkflowCompletedEvent({
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
      result: finalResult,
    });

    return finalResult;
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
