// Managed weaver bot batch workflow - processes multiple tasks via forEach scope.
// Run `weaver eject` to customize.

import { weaverLoadConfig } from '../node-types/load-config.js';
import { weaverDetectProvider } from '../node-types/detect-provider.js';
import { weaverReceiveTask } from '../node-types/receive-task.js';
import { weaverBuildContext } from '../node-types/build-context.js';
import { weaverPlanTask } from '../node-types/plan-task.js';
import { weaverApprovalGate } from '../node-types/approval-gate.js';
import { weaverAbortTask } from '../node-types/abort-task.js';
import { weaverExecValidateRetry } from '../node-types/exec-validate-retry.js';
import { weaverGitOps } from '../node-types/git-ops.js';
import { weaverSendNotify } from '../node-types/send-notify.js';
import { weaverBotReport } from '../node-types/bot-report.js';

/**
 * Batch workflow bot. Processes multiple sub-tasks sequentially,
 * running the full plan-approve-execute cycle for each.
 *
 * @flowWeaver workflow
 *
 * @node cfg       weaverLoadConfig       [color: "teal"]    [icon: "settings"]      [position: 200 200]
 * @node detect    weaverDetectProvider   [color: "cyan"]    [icon: "search"]        [position: 400 200]
 * @node receive   weaverReceiveTask      [color: "blue"]    [icon: "send"]          [position: 600 200]
 * @node context   weaverBuildContext     [color: "teal"]    [icon: "code"]          [position: 800 200]
 * @node plan      weaverPlanTask         [color: "blue"]    [icon: "psychology"]    [position: 1000 200]
 * @node approve   weaverApprovalGate     [color: "orange"]  [icon: "send"]          [position: 1200 200]
 * @node abort     weaverAbortTask        [color: "red"]     [icon: "code"]          [position: 1400 400]
 * @node execRetry weaverExecValidateRetry [color: "purple"] [icon: "code"]          [position: 1400 200]
 * @node gitOps    weaverGitOps           [color: "green"]   [icon: "code"]          [position: 1600 100]
 * @node notify    weaverSendNotify       [color: "yellow"]  [icon: "send"]          [position: 1600 300]
 * @node report    weaverBotReport        [color: "green"]   [icon: "description"]   [position: 1800 200]
 *
 * @path Start -> cfg -> detect -> receive -> context -> plan -> approve -> execRetry -> gitOps -> report -> Exit
 * @path execRetry -> notify
 * @path approve:fail -> abort
 *
 * @connect notify.onSuccess -> report.execute
 * @connect abort.onSuccess -> report.execute
 *
 * @connect gitOps.ctx -> report.mainCtx
 * @connect abort.ctx -> report.abortCtx
 *
 * @connect report.summary -> Exit.summary
 *
 * @position Start 0 200
 * @position Exit 2000 200
 *
 * @param execute [order:-1] - Execute
 * @param taskJson [order:0] [optional] - Batch task instruction (JSON)
 * @param projectDir [order:1] [optional] - Project directory
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] [hidden] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaverBotBatch(
  execute: boolean,
  params: { taskJson?: string; projectDir?: string },
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // (auto-generated by compiler)
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
