export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  generate: (opts: { projectDir?: string }) => string;
}

export const weaverBotTemplate: WorkflowTemplate = {
  id: 'weaver-bot',
  name: 'Weaver Bot: Autonomous workflow creator',
  description: 'AI-powered bot that creates, modifies, and manages Flow Weaver workflows autonomously from natural language instructions',
  category: 'bot',
  generate: (_opts) => {
    return `// Generated by flow-weaver-pack-weaver. Compile before running:
//   flow-weaver compile weaver-bot.ts
//   flow-weaver weaver bot "Create a hello world workflow"

import { weaverLoadConfig } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverDetectProvider } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverReceiveTask } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverRouteTask } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverReadWorkflow } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverBuildContext } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverPlanTask } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverApprovalGate } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverAbortTask } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverExecValidateRetry } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverGitOps } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverSendNotify } from '@synergenius/flow-weaver-pack-weaver/node-types';
import { weaverBotReport } from '@synergenius/flow-weaver-pack-weaver/node-types';

/**
 * Autonomous workflow bot.
 *
 * @flowWeaver workflow
 *
 * @node cfg      weaverLoadConfig       [color: "slate"]    [icon: "settings"]       [position: 80 200]
 * @node detect   weaverDetectProvider   [color: "cyan"]     [icon: "search"]         [position: 230 200]
 * @node receive  weaverReceiveTask      [color: "indigo"]   [icon: "inbox"]          [position: 400 200]
 * @node route    weaverRouteTask        [color: "violet"]   [icon: "alt_route"]      [position: 570 200]
 * @node readWf   weaverReadWorkflow     [color: "sky"]      [icon: "visibility"]     [position: 740 450]
 * @node context  weaverBuildContext     [color: "teal"]     [icon: "auto_stories"]   [position: 740 200]
 * @node plan     weaverPlanTask         [color: "blue"]     [icon: "psychology"]     [position: 910 200]
 * @node approve  weaverApprovalGate     [color: "amber"]    [icon: "gavel"]          [position: 1080 200]
 * @node abort    weaverAbortTask        [color: "red"]      [icon: "cancel"]         [position: 1250 450]
 * @node execRetry weaverExecValidateRetry [color: "purple"] [icon: "replay"]         [position: 1250 200]
 * @node gitOps   weaverGitOps           [color: "stone"]    [icon: "commit"]         [position: 1420 100]
 * @node notify   weaverSendNotify       [color: "yellow"]   [icon: "notifications"]  [position: 1420 300]
 * @node report   weaverBotReport        [color: "green"]    [icon: "summarize"]      [position: 1600 200]
 *
 * @path Start -> cfg -> detect -> receive -> route -> context -> plan -> approve -> execRetry -> gitOps -> report -> Exit
 * @path Start -> execRetry -> notify -> report -> Exit
 * @path Start -> route:fail -> readWf -> report -> Exit
 * @path Start -> approve:fail -> abort -> report -> Exit
 *
 * @connect route.taskJson -> readWf.taskJson
 * @connect route.projectDir -> readWf.projectDir
 * @connect readWf.resultJson -> report.readResult
 * @connect readWf.taskJson -> report.taskJson
 * @connect route.taskJson -> context.taskJson
 * @connect context.contextBundle -> plan.contextBundle
 * @connect plan.planJson -> approve.planJson
 * @connect approve.rejectionReason -> abort.rejectionReason
 * @connect approve.taskJson -> abort.taskJson
 * @connect approve.projectDir -> abort.projectDir
 * @connect abort.resultJson -> report.abortResult
 * @connect abort.taskJson -> report.taskJson
 * @connect approve.planJson -> execRetry.planJson
 * @connect approve.taskJson -> execRetry.taskJson
 * @connect execRetry.filesModified -> gitOps.filesModified
 * @connect execRetry.projectDir -> gitOps.projectDir
 * @connect cfg.config -> gitOps.config
 * @connect execRetry.resultJson -> notify.resultJson
 * @connect execRetry.projectDir -> notify.projectDir
 * @connect cfg.config -> notify.config
 * @connect execRetry.resultJson -> report.mainResult
 * @connect execRetry.filesModified -> report.filesModified
 * @connect receive.taskJson -> report.taskJson
 * @connect gitOps.gitResultJson -> report.gitResultJson
 * @connect report.summary -> Exit.summary
 *
 * @position Start 0 200
 * @position Exit 1750 200
 *
 * @param execute [order:-1] - Execute
 * @param taskJson [order:0] [optional] - Task instruction (JSON)
 * @param projectDir [order:1] [optional] - Project directory
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaverBot(
  execute: boolean,
  taskJson?: string,
  projectDir?: string,
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // (auto-generated by compiler)
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
`;
  },
};
