export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  generate: (opts: { projectDir?: string }) => string;
}

export const weaverTemplate: WorkflowTemplate = {
  id: 'weaver',
  name: 'Weaver: Autonomous workflow runner',
  description: 'AI-powered runner that executes any Flow Weaver workflow autonomously, with auto-detected providers and notification support',
  category: 'automation',
  generate: (_opts) => {
    return `// Generated by flowweaver-pack-weaver. Compile before running:
//   flow-weaver compile weaver.ts
//   flow-weaver run weaver.ts
// Or use the CLI directly: npx weaver weaver.ts
//
// Node types are provided by @synergenius/flowweaver-pack-weaver.
// Install it: npm install @synergenius/flowweaver-pack-weaver

import { weaverLoadConfig } from '@synergenius/flowweaver-pack-weaver/node-types';
import { weaverDetectProvider } from '@synergenius/flowweaver-pack-weaver/node-types';
import { weaverResolveTarget } from '@synergenius/flowweaver-pack-weaver/node-types';
import { weaverExecuteTarget } from '@synergenius/flowweaver-pack-weaver/node-types';
import { weaverSendNotify } from '@synergenius/flowweaver-pack-weaver/node-types';
import { weaverReport } from '@synergenius/flowweaver-pack-weaver/node-types';

/**
 * @flowWeaver workflow
 * @node cfg weaverLoadConfig [color: "teal"] [icon: "settings"] [position: 100 0]
 * @node detect weaverDetectProvider [color: "cyan"] [icon: "search"] [position: 250 0]
 * @node target weaverResolveTarget [color: "blue"] [icon: "code"] [position: 400 0]
 * @node exec weaverExecuteTarget [color: "purple"] [icon: "psychology"] [position: 550 0]
 * @node notify weaverSendNotify [color: "yellow"] [icon: "notifications"] [position: 700 0]
 * @node rep weaverReport [color: "green"] [icon: "description"] [position: 850 0]
 * @path Start -> cfg -> detect -> target -> exec -> notify -> rep -> Exit
 * @position Start 0 0
 * @position Exit 1000 0
 * @connect rep.summary -> Exit.summary
 * @param execute [order:-1] - Execute
 * @param params [order:0] - Params
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns summary [order:0] - Summary text
 */
export async function weaver(
  execute: boolean,
  params: Record<string, never> = {},
  __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; summary: string | null }> {
  // @flow-weaver-body-start
  // (auto-generated by compiler)
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, summary: null };
}
`;
  },
};
